/**
 * Generated by Supabase CLI.
 *
 * Until your first generation run, this placeholder keeps TypeScript imports valid.
 *
 * Regenerate via:
 * - SUPABASE_PROJECT_ID=abcdefghijklmnopqrst npm run db:types
 */
export type Database = unknown;

